spring.application.name=authService

spring.datasource.url=jdbc:mysql://localhost:3306/auth_service_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

jwt.secret= my-secret-key-1234@bjbjjkj$703622kk
jwt.expiration= 3600000
